### ISSUE TITLE
cannot find symbol method addCallback(<anonymous Callback>)

### ISSUE THREAD

**Issue by sivabe35** [GrenderG/TinyList#1]
Snackbar.addCallback 

cannot resolve  method` 'addCallback(anonymous  android.support.design.widget.Snackbar.Callback)'`

im importing
` import android.support.design.widget.Snackbar;`

**Comment by GrenderG** [comment]
That's weird since that method [obviously exists](https://developer.android.com/reference/android/support/design/widget/BaseTransientBottomBar.html#addCallback(android.support.design.widget.BaseTransientBottomBar.BaseCallback<B>)).  Have you changed something from the `build.gradle` file or the code itself?

**Comment by sivabe35** [comment]
may be this because of I downgraded support design: library to  25.0.0 

anyhow I fixed this issue with `Snackbar.setCallback()`  .

thankQ @GrenderG
